version: '3'
services:
  back:
    build: ./back
    environment: 
      - MONGODB_URL=mongodb://mongo:mongo@mongodb
    ports:
      - 8000:8000
    volumes:
        - ./back:/app
    tty: true
#    environment:
#      DEBUG_COLORS: "true"
#      TERM: xterm-256color
#      COLORTERM: truecolor


  mongodb:
    image: mongo:5.0
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongo
      - MONGO_INITDB_ROOT_PASSWORD=mongo
    command: --setParameter processUmask=022
    volumes:
      - ./mongo:/data/db
    ports:
      - 27017:27017
