version: '3'
services:
  back:
    build: ./back
    environment: 
      - MONGODB_URL=mongodb://mongo:mongo@mongodb
      - DATABASE=acropyx2-dev
    ports:
      - 8000:8000
    volumes:
        - ./back:/app
    tty: true

#  back-test:
#    build: ./back
#    environment:
#      - MONGODB_URL=mongodb://mongo:mongo@mongodb
#      - DATABASE=acropyx2-testing
#    volumes:
#      - ./back:/app

  public:
    image: node:18-alpine
    command: sh -c "npm ci && npm run dev"
    working_dir: /app
    ports:
      - 3000:3000
    volumes:
      - ./frontend-public:/app

  manager:
    image: node:18-alpine
    command: sh -c "npm ci && npm run dev"
    working_dir: /app
    ports:
      - 3001:3001
    volumes:
      - ./frontend-manager:/app

  mongodb:
    image: mongo:5.0
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongo
      - MONGO_INITDB_ROOT_PASSWORD=mongo
    command: --setParameter processUmask=022
    volumes:
      - ./mongo:/data/db
    ports:
      - 27017:27017
